services:
  - mysql

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export PATH="/home/travis/.deno/bin:$PATH"

script:
  - deno test src/tests/auth.test.ts --allow-net=127.0.0.1 --allow-read=config.json -c src/tsconfig.json